apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-u12g
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-u12g
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-u12g
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-u12g
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-u12g
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tgll-tenant/rhtap-demo-app/hacbs-test-project-u12g@sha256:b25a78ebed9444c6470db2ee45e3569d5b62d46d003d83b9817dc5df4d5dd184
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
